import type { Metadata } from "next";
import { Geist, Geist_Mono, Gowun_Dodum, IBM_Plex_Sans_KR } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fastBody = Gowun_Dodum({
  weight: "400",
  variable: "--font-fast-body",
  subsets: ["latin"],
  preload: false,
});

const fastDisplay = IBM_Plex_Sans_KR({
  weight: ["500", "600"],
  variable: "--font-fast-display",
  subsets: ["latin"],
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${fastBody.variable} ${fastDisplay.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
